services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:alpine # Указываем образ PostgreSQL
    ports:
      - "5432"
    environment:
      POSTGRES_USER: pguser # Устанавливаем пользователя базы данных
      POSTGRES_PASSWORD: pgpassword # Устанавливаем пароль
      POSTGRES_DB: study_on # Имя базы данных
    volumes:
      - database_data:/var/lib/postgresql/data # Добавляем том для хранения данных
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

volumes:
  database_data: # Добавляем определение тома для базы данных
