services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Конфигурация для HttpClient
  App\Service\HttpClient:
    arguments: []

  # Конфигурация для UserBillingClient
  App\Service\UserBillingClient:
    arguments:
      $billingUrl: "%env(BILLING_URL)%"
      $httpClient: '@App\Service\HttpClient'

  # Конфигурация для CourseBillingClient
  App\Service\CourseBillingClient:
    arguments:
      $billingUrl: "%env(BILLING_URL)%"
      $httpClient: '@App\Service\HttpClient'

  # Конфигурация для TransactionBillingClient
  App\Service\TransactionBillingClient:
    arguments:
      $billingUrl: "%env(BILLING_URL)%"
      $httpClient: '@App\Service\HttpClient'

  # Конфигурация для BillingClient
  App\Service\BillingClient:
    arguments:
      $userBillingClient: '@App\Service\UserBillingClient'
      $courseBillingClient: '@App\Service\CourseBillingClient'
      $transactionBillingClient: '@App\Service\TransactionBillingClient'
